### ISSUE TITLE
Remove alert

### ISSUE THREAD

**Issue by rechvagner** [jangevaare/cbpi-mutually-exclusive-actors#1]
Can I remove these lines? This alert is displayed at all times.

`           else:
                    self.api.notify(headline="Powering of actor prevented", message="This is due to the current power state of it's dependency, %s" % (dependency_name), timeout=None, type="danger")
raise UserWarning("Powering of actor prevented by the state of it's dependency")` 
  
![dependence](https://user-images.githubusercontent.com/31131745/45157884-bb57ea80-b1b8-11e8-9f4c-1fb368b97255.JPG)
![erro](https://user-images.githubusercontent.com/31131745/45157885-bb57ea80-b1b8-11e8-927a-e5049eb46a72.JPG)

**Comment by jangevaare** [comment]
This should only be displayed if there's a conflict in dependent actors. Is that not the case?

**Comment by rechvagner** [comment]
My config:

Actor Resistencia 1 in GPIO 19 (GPIOSample)
Actor Resistencia 2 in GPIO 6 (GPIOSample)

Ketlle Mostura use Resistencia 1 (PIDBoil)
Kettle Fly Sparge use Dependence (PIDArduino)

Any other actor no uses these GPIO or Actors.

Ps sorry for bad english.

**Comment by jangevaare** [comment]
From what I understand, with your configuration the expected behaviour is that actor "Resistencia 1 (Dependence)" will trigger this notification when you attempt to activate it while "Resistencia 2" is active. It wil also prevent "Resistencia 1 (Dependence)" from turning on.

Is this what happens? Are you trying to do something else?

**Comment by rechvagner** [comment]
Resistencia 1 is main mash.
Resistencia 2 fly (less important)

I need Resistencia 2 turn on only if Resistencia 1 is turned off

My config is correctly?

**Comment by jangevaare** [comment]
I think you have configured this plugin correctly.

From your screenshot it looks like both kettles are on, which would result in this notification (as intended)

If you understand this all and would just like to make the notification go away, you could comment out that line of code and that would take care of it.

The plugin could also be modified such that there is an option to suppress the notifications themselves pretty easily.

To be clear, I think what you want is this:

```
if idx == int(self.dependency):
                if (value.state == 0) & (self.dependency_type == "Restriction"):
                    self.api.switch_actor_on(int(self.base), power=power)
                elif (value.state == 1) & (self.dependency_type == "Prerequisite"):
                    self.api.switch_actor_on(int(self.base), power=power)
                else:
                    # self.api.notify(headline="Powering of actor prevented", message="This is due to the current power state of it's dependency, %s" % (dependency_name), timeout=None, type="danger")
                    raise UserWarning("Powering of actor prevented by the state of it's dependency")
```

**Comment by jangevaare** [comment]
I am no longer using CBPi so I can't test myself, but I created a branch of this plugin with an option to set notification duration. Set to 0 to disable the notifications. Can you test it? To test, stop CBPi, then navigate to the folder for this plugin in your craftbeerpi installation and run

```
git fetch
git checkout notification_options
```

Then restart CBPi. Reconfigure your dependentactor with the notification duration set to 0.

**Comment by rechvagner** [comment]
I made the change below to ensure that Resistencia 2 is turned off

``` 
else:
    self.api.switch_actor_off(int(self.base))
     # self.api.notify(headline="Powering of actor prevented", message="This is due to the current power state of it's dependency, %s" % (dependency_name), timeout=None, type="danger")
    raise UserWarning("Powering of actor prevented by the state of it's dependency")
```

It's not an elegant solution, but ... it worked 

Thanks for help me

**Comment by jangevaare** [comment]
That's a good idea. In my testing the `raise UserWarning` was sufficient to prevent activation, but I will add that.
